### PR TITLE
Check ERANGE error from getcwd

### LINKED ISSUE #1425: compile: getcwd(): Result too large
Hi,

We're using `capnp` with [Bazel](https://bazel.build/), which likes to use long paths and in some situations will cause `capnp compile` to fail.

```
--stderr:
*** Fatal uncaught kj::Exception: kj/filesystem-disk-unix.c++:1717: failed: getcwd(): Result too large
thread 'main' panicked at 'schema compiler command: Error { kind: Failed, description: "Error while trying to execute `capnp compile`: Failed: Premature end of file.  Please verify that version 0.5.2 or higher of the capnp executable is installed on your system. See https://capnproto.org/install.html" }', external/raze__segments_rpc__0_0_0/rpc/build.rs:17:10
stack backtrace:
```

The offending snippet:

https://github.com/capnproto/capnproto/blob/767b8a30ee100f1c648a75c9aaf252212d904c17/c%2B%2B/src/kj/filesystem-disk-unix.c%2B%2B#L1711-L1719

Reading through the documentation for [`getcwd`](https://linux.die.net/man/3/getcwd), it seems that `ERANGE` should be checked instead of (in addition to?) `ENAMETOOLONG`. Am I correct in reading that `ENAMETOOLONG` is actually only applicable to `getwd`? I don't see any mention of `ENAMETOOLONG` in the Open Group Specification for [`getcwd`](https://pubs.opengroup.org/onlinepubs/007904975/functions/getcwd.html).

So I think there may be two fixes available.

1. Use `ERANGE` instead of `ENAMETOOLONG`.
2. Use [`std::filesystem::current_path();`](https://en.cppreference.com/w/cpp/filesystem/current_path) (introduced in C++17) as described in this [Stack Overflow answer](https://stackoverflow.com/a/2203694).

I'm not too deep into C++ so I'm unsure of which of the two proposed solutions is correct 😄 What are your thoughts?

### PR DESCRIPTION
**Pull request by uhthomas**
Fixes #1425

### CODE REVIEW

File: c++/src/kj/filesystem-disk-test.c++ [hunk 1]
```diff
@@ -945,5 +946,30 @@ KJ_TEST("DiskFile holes") {
...
+  // Paths can be PATH_MAX, but the segments which make up that path typically
+  // can't exceed 255 bytes.
+  auto maxPathSegment = std::string(255, 'a');
+
+  // Create a path which exceeds the 256 byte buffer used in
+  // computeCurrentPath. 
+  auto subdir = dir->openSubdir(Path({
+    maxPathSegment,
+    maxPathSegment,
+    "some_path_longer_than_256_bytes"
```
Comment (kentonv) [inline c++/src/kj/filesystem-disk-test.c++:965]: Running the CI now and we'll see what it says, but I'm going to guess this part fails on Windows and maybe some other OSes. Might need to limit to Linux.

File: c++/src/kj/filesystem-disk-unix.c++ [hunk 2]
```diff
@@ -1705,12 +1705,15 @@ private:
       }
     }
 
+    // TODO(someday): Use MAX_PATH from <limits.h>?
```
Comment (kentonv) [inline c++/src/kj/filesystem-disk-unix.c++:1708]: I intentionally didn't want to over-allocate here.

File: c++/src/kj/filesystem-disk-unix.c++ [hunk 3]
```diff
@@ -1705,12 +1705,15 @@ private:
...
+    // TODO(someday): Use std::filesystem::current_path() when compiling with
```
Comment (kentonv) [inline c++/src/kj/filesystem-disk-unix.c++:1709]: KJ generally prefers to avoid the C++ standard library and go direct to OS APIs, so I'd remove this comment.

**Review by kentonv — COMMENTED** [review]
Thanks for fixing this!

File: c++/src/kj/filesystem-disk-test.c++ (hunk 1 above)
Comment (uhthomas) [reply c++/src/kj/filesystem-disk-test.c++:965]: Interesting thought.

I've pushed a change which addresses the unused result errors. Let's see if CI is any happier now, and if not I'm happy to restrict this to Linux.

Comment (kentonv) [reply c++/src/kj/filesystem-disk-test.c++:965]: It actually does appear that it passed on windows-latest so maybe Windows does support long paths after all? Somehow I thought it was limited to 256 chars total for the whole path.

Actually I bet it works specifically because the KJ filesystem impl uses the crazy `\\?\` prefix that bypasses a huge amount of Win32 legacy cruft, heh.

Comment (kentonv) [reply c++/src/kj/filesystem-disk-test.c++:965]: Wait no. The windows-latest build is broken and is not even doing a build, but reporting success. :man_facepalming:

File: c++/src/kj/filesystem-disk-test.c++ [hunk 4]
```diff
@@ -945,5 +946,30 @@ KJ_TEST("DiskFile holes") {
...
+
+  // Create a path which exceeds the 256 byte buffer used in
+  // computeCurrentPath.
+  auto subdir = dir->openSubdir(Path({
+    maxPathSegment,
+    maxPathSegment,
+    "some_path_longer_than_256_bytes"
+  }), WriteMode::CREATE | WriteMode::CREATE_PARENT);
+
+  KJ_SYSCALL(fchdir(KJ_ASSERT_NONNULL(subdir->getFd())));
```
Comment (kentonv) [inline c++/src/kj/filesystem-disk-test.c++:968]: You need to arrange to change directories back at the end of the test, otherwise:
* All remaining tests (e.g. unit tests in other source files) will run in the wrong directory, possibly leading to unexpected behavior.
* `TempDir`'s destructor won't be able to delete the temporary directory... I'm kind of surprised this isn't causing a failure, actually.

`fchdir` doesn't exist on Windows, so we definitely at least have to wrap this test in `#if !_WIN32`. That's fine since it's testing for a bug that was Unix-specific anyway.

Comment (kentonv) [reply c++/src/kj/filesystem-disk-test.c++:968]: Something like...

```
int origDir = open(cwd, O_RDONLY | O_DIRECTORY);
...
KJ_DEFER(fchdir(origDir));
```

File: c++/src/kj/filesystem-disk-test.c++ [hunk 5]
```diff
@@ -945,5 +946,30 @@ KJ_TEST("DiskFile holes") {
...
+
+  // Test computeCurrentPath indirectly.
+  KJ_EXPECT(newDiskFilesystem());
```
Comment (kentonv) [inline c++/src/kj/filesystem-disk-test.c++:971]: KJ_EXPECT doesn't really make sense here since `newDiskFilesystem()` doesn't return a boolean. I think this only complies by accident.

Comment (kentonv) [reply c++/src/kj/filesystem-disk-test.c++:971]: To be clear, you can just remove the `KJ_EXCEPT`. This function wont produce a warning if the result is unused. `fchdir` is apparently specially marked to produce such a warning.

File: c++/src/kj/filesystem-disk-test.c++ (hunk 4 above)
Comment (uhthomas) [reply c++/src/kj/filesystem-disk-test.c++:970]: Sounds good to me! Thank you for all the help and snippets 😄

File: c++/src/kj/filesystem-disk-test.c++ (hunk 5 above)
Comment (uhthomas) [reply c++/src/kj/filesystem-disk-test.c++]: Done! Thank you again for being so helpful!

File: c++/src/kj/filesystem-disk-test.c++ (hunk 1 above)
Comment (uhthomas) [reply c++/src/kj/filesystem-disk-test.c++:966]: 😅 Restricted the test to Unix.

**Comment by kentonv** [comment]
Thanks!
