### PR TITLE
Fixes for group assignment in dynamic API and BufferInputStreamWrapper::tryRead

### LINKED ISSUE #1980: BufferedInputStreamWrapper::tryRead fails on EOF
Currently, the implementation of `BufferedInputStreamWrapper::tryRead` will throw on premature EOF due to forwarding to `InputStream::read` if the buffer is insufficient to fill the request:

https://github.com/capnproto/capnproto/blob/737dba8da94fcde061ebd8b9b3e7efff727b9877/c%2B%2B/src/kj/io.c%2B%2B#L156
https://github.com/capnproto/capnproto/blob/737dba8da94fcde061ebd8b9b3e7efff727b9877/c%2B%2B/src/kj/io.c%2B%2B#L164

Wouldn't it make more sense to forward the read requests to `InputStream::tryRead` instead?

### PR DESCRIPTION
**Pull request by alexrobomind**
This fixes #1980 and #2067 and adds a test case that would have fired on #2067. Based on master because I still work on v1 and didn't want to port it forward and back again.

### CODE REVIEW

File: c++/src/capnp/dynamic.c++ [hunk 1]
```diff
@@ -661,6 +661,8 @@ void DynamicStruct::Builder::set(StructSchema::Field field, const DynamicValue::
           dst.set(field, src.get(field));
         }
       }
+	  
+	  return;
```
Comment (kentonv) [inline c++/src/capnp/dynamic.c++]:
```suggestion
      return;
```

Comment (alexrobomind) [reply c++/src/capnp/dynamic.c++]: Yeah, noticed it too in the editor. Looked the same offline, sorry.

Comment (kentonv) [reply c++/src/capnp/dynamic.c++]: Oh, you did it right as I was commenting.

**Review by kentonv — APPROVED** [review]
Thanks. Looks good, will merge after CI passes.

**Comment by alexrobomind** [comment]
Thanks a lot. Looking in the log, the new test seems to be there. Also, man you're fast ...

**Comment by kentonv** [comment]
> Also, man you're fast ...

Not normally! You just happened to send this right as I was reaching inbox zero before heading out on vacation. :)

**Comment by alexrobomind** [comment]
Lucky me :-P. Enjoy your holidays.

**Comment by fhanau** [comment]
@kentonv this is also needed on the v2 branch right? I can make a PR.

**Comment by kentonv** [comment]
@fhanau Yeah. Actually there's probably a lot of patches on the master branch that should be picked into v2.
