### PR TITLE
Clamp writes on bad OSes that get confused by sizes greater than INT32_MAX.

### LINKED ISSUE #2187: capnp::writeMessageToFd fails for large messages on macOS
In our application, messages that should be written to files can become quite large, depending on user input. The Messages are created using `capnp::MallocMessageBuilder`, passing an externally allocated (potentially very big) first segment to it.

Under some circumstances I found `capnp::writeMessageToFd` throwing an exception which is caused by the call to `::writev` here: https://github.com/capnproto/capnproto/blob/d4ba9809ddd89b85d401353b9dfb5b59cf705db7/c%2B%2B/src/kj/io.c%2B%2B#L405

I looked at the issue under the debugger and found out that the `iov` array passed in that scenario contains three elements of the sizes 16, 2132300288 and 76629368 bytes. `::writev` then returns -1 and `errno` is set to `EINVAL`. I read the online man pages for `writev` multiple times finding no clues why this should fail until I eventually ended up looking at the man pages on my actual system in the terminal. That felt so old school but revealed that it indeed contains quite a bit of extra information neither found in the archived macOS man pages or linux man pages that can be found online. To my surprise I did not find any only version of the man pages for the macOS 14.1 SDK, so I'll paste the content of it below.

The relevant parts are:
> write() and pwrite() will fail if the parameter nbyte exceeds INT_MAX, and they do not attempt a partial write.

and further below under ERRORS specific for `writev`

> [EINVAL]		The sum of the iov_len values in the iov array overflows a 32-bit integer.

Looking at the values of my test case again this indeed is the case here. So I think there either needs to be some logic that splits the data into multiple write calls. Do you agree?

```
WRITE(2)		      System Calls Manual		      WRITE(2)

NAME
     pwrite, write, pwritev, writev – write output

LIBRARY
     Standard C Library (libc, -lc)

SYNOPSIS
     #include <unistd.h>

     ssize_t
     pwrite(int fildes, const void *buf, size_t nbyte, off_t offset);

     ssize_t
     write(int fildes, const void *buf, size_t nbyte);

     #include <sys/uio.h>

     ssize_t
     writev(int fildes, const struct iovec *iov, int iovcnt);

     ssize_t
     pwritev(int fildes, const struct iovec *iov, int iovcnt, off_t offset);

DESCRIPTION
     write() attempts to write nbyte of data to the object referenced by the
     descriptor fildes from the buffer pointed to by buf.  writev() performs
     the same action, but gathers the output data from the iovcnt buffers
     specified by the members of the iov array: iov[0], iov[1], ...,
     iov[iovcnt-1].  pwrite() and pwritev() perform the same functions, but
     write to the specified position in the file without modifying the file
     pointer.

     For writev() and pwritev(), the iovec structure is defined as:

	   struct iovec {
		   char   *iov_base;  /* Base address. */
		   size_t iov_len;    /* Length. */
	   };

     Each iovec entry specifies the base address and length of an area in
     memory from which data should be written.	writev() and pwritev() will
     always write a complete area before proceeding to the next.

     On objects capable of seeking, the write() starts at a position given by
     the pointer associated with fildes, see lseek(2).	Upon return from
     write(), the pointer is incremented by the number of bytes which were
     written.

     Objects that are not capable of seeking always write from the current
     position.	The value of the pointer associated with such an object is
     undefined.

     If the real user is not the super-user, then write() clears the set-user-
     id bit on a file.	This prevents penetration of system security by a user
     who “captures” a writable set-user-id file owned by the super-user.

     When using non-blocking I/O on objects, such as sockets, that are subject
     to flow control, write() and writev() may write fewer bytes than
     requested; the return value must be noted, and the remainder of the
     operation should be retried when possible.

     write() and pwrite() will fail if the parameter nbyte exceeds INT_MAX,
     and they do not attempt a partial write.

RETURN VALUES
     Upon successful completion the number of bytes which were written is
     returned.	Otherwise, a -1 is returned and the global variable errno is
     set to indicate the error.

ERRORS
     The write(), writev(), pwrite(), and pwritev() system calls will fail and
     the file pointer will remain unchanged if:

     [EDQUOT]		The user's quota of disk blocks on the file system
			containing the file is exhausted.

     [EFAULT]		Part of iov or data to be written to the file points
			outside the process's allocated address space.

     [EINVAL]		The pointer associated with fildes is negative.

     The write() and pwrite() system calls will fail and the file pointer will
     remain unchanged if:

     [EAGAIN]		The file is marked for non-blocking I/O, and no data
			could be written immediately.

     [EBADF]		fildes is not a valid file descriptor open for
			writing.

     [ECONNRESET]	A write is attempted on a socket that is not
			connected.

     [EFBIG]		An attempt is made to write a file that exceeds the
			process's file size limit or the maximum file size.

     [EFBIG]		The file is a regular file, nbyte is greater than 0,
			and the starting position is greater than or equal to
			the offset maximum established in the open file
			description associated with fildes.

     [EINTR]		A signal interrupts the write before it could be
			completed.

     [EINVAL]		The value provided for nbyte exceeds INT_MAX.

     [EIO]		An I/O error occurs while reading from or writing to
			the file system.

     [ENETDOWN] 	A write is attempted on a socket and the local network
			interface used to reach the destination is down.

     [ENETUNREACH]	A write is attempted on a socket and no route to the
			network is present.

     [ENOSPC]		There is no free space remaining on the file system
			containing the file.

     [ENXIO]		A request is made of a nonexistent device, or the
			request is outside the capabilities of the device.

     [EPIPE]		An attempt is made to write to a pipe that is not open
			for reading by any process.

     [EPIPE]		An attempt is made to write to a socket of type
			SOCK_STREAM that is not connected to a peer socket.

     [EDEADLK]		The file is a “dataless” file that requires
			materialization and the I/O policy of the current
			thread or process disallows dataless file
			materialization (see getiopolicy_np(3)).

     The write() and writev() calls may also return the following errors:

     [EAGAIN]		See EWOULDBLOCK, below.

     [EWOULDBLOCK]	The file descriptor is for a socket, is marked
			O_NONBLOCK, and write would block.  The exact error
			code depends on the protocol, but EWOULDBLOCK is more
			common.

     In addition, writev() may return one of the following errors:

     [EDESTADDRREQ]	The destination is no longer available when writing to
			a UNIX domain datagram socket on which connect(2) or
			connectx(2) had been used to set a destination
			address.

     [ENOBUFS]		The mbuf pool has been completely exhausted when
			writing to a socket.

     The writev() and pwritev() calls may also return the following errors:

     [EINVAL]		Iovcnt is less than or equal to 0, or greater than
			UIO_MAXIOV.

     [EINVAL]		One of the iov_len values in the iov array is
			negative.

     [EINVAL]		The sum of the iov_len values in the iov array
			overflows a 32-bit integer.

     The pwrite() and pwritev() calls may also return the following errors:

     [EINVAL]		The specified file offset is invalid.

     [ESPIPE]		The file descriptor is associated with a pipe, socket,
			or FIFO.

LEGACY SYNOPSIS
     #include <sys/types.h>
     #include <sys/uio.h>
     #include <unistd.h>

     These include files are needed for all three functions.

SEE ALSO
     fcntl(2), lseek(2), open(2), pipe(2), select(2), compat(5)

STANDARDS
     The write() function call is expected to conform to IEEE Std 1003.1-1990
     (“POSIX.1”).  The writev() and pwrite() functions are expected to conform
     to X/Open Portability Guide Issue 4, Version 2 (“XPG4.2”).  pwritev() is
     nonstandard.

HISTORY
     The pwrite() function call appeared in AT&T System V Release 4 UNIX.  The
     writev() function call appeared in 4.2BSD.  A write() function call
     appeared in Version 6 AT&T UNIX.

macOS 14.1			 June 3, 2021			    macOS 14.1
```

### PR DESCRIPTION
**Pull request by kentonv**
Fixes #2187.

Unsure how to test this as making unit tests allocate multiple gigs of RAM and then try to write them to a file doesn't seem like a great idea.

### CODE REVIEW

File: c++/src/kj/io.c++ [hunk 1]
```diff
@@ -401,11 +417,47 @@ void FdOutputStream::write(ArrayPtr<const ArrayPtr<const byte>> pieces) {
...
+
     // Issue the write.
     ssize_t n = 0;
-    KJ_SYSCALL(n = ::writev(fd, current, iov.end() - current), fd);
+    KJ_SYSCALL(n = ::writev(fd, current, iovCount), fd);
     KJ_ASSERT(n > 0, "writev() returned zero.");
 
+#if __APPLE__
+    // If we patched the list above, unpatch now.
+    if (editedPiece != nullptr) {
```
Comment (mikea) [inline c++/src/kj/io.c++:456]: What is the exception flow? Should we worry about it?

**Review by mikea — APPROVED** [review]

File: c++/src/kj/io.c++ (hunk 1 above)
Comment (kentonv) [reply c++/src/kj/io.c++:456]: The iov array was allocated on the stack earlier in this function, line 403. So on exception it harmlessly goes away.

**Comment by kentonv** [comment]
Also cherry-picked to master branch as f6d17ac16986d6c67e1dcefdaa37cae4ed351a9a.
